#ifndef NENEFOLIO_RENAME_JOURNAL_OUTCOME_H
#define NENEFOLIO_RENAME_JOURNAL_OUTCOME_H
enum rename_journal_outcome : unsigned char
{
    RENAME_JOURNAL_ACCEPTED,
    RENAME_JOURNAL_INVALID,
    RENAME_JOURNAL_UNSUPPORTED_VERSION,
    RENAME_JOURNAL_OUT_OF_MEMORY
};
#endif
