/* 利用者に見える文言の ID（ADR 0030 の決定 1）。閉じた列挙で、文言そのものは ui_text.c の
 * 表 1 か所だけが持つ。表の網羅は CNF-009（eng/conformance-rules.json の lineTables）が守り、
 * 直書きの再発は CNF-010 が拒む（C-018）。
 * 群: FAILURE（folio_state_outcome と 1 対 1）・COMMAND（folio_command と 1 対 1）・HELP・
 * STATUS・ACTION・CHIP・PROMPT・APP・GLYPH・PLACEHOLDER・TITLE・EMPTY。
 * 置換子（{k} {n} {offset} {name} {from} {to}）を持つ文言は ui_text_format が埋める。 */
#ifndef NENEFOLIO_UI_TEXT_H
#define NENEFOLIO_UI_TEXT_H

#include "folio_language.h"
#include "ui_text_format_outcome.h"

#include <stddef.h>

/* 置換子に入れる値の束（ui_text_request.h の完全型）。ここでは名前だけ知っていれば足りる。 */
struct ui_text_request;

/* 表の 1 行が UTF-16 で収まる上限（決定 5）。W 系 API へ渡す経路はこの大きさの
 * スタックのバッファを使い、確保しない。日本語の最長 64 単位の 4 倍を取ってある。
 * 全 ID がここに収まることは単体が全 ID を回して固定する。 */
constexpr size_t ui_text_unit_limit = 256;

enum ui_text : unsigned char
{
    UI_TEXT_EMPTY,
    UI_TEXT_FAILURE_DATA_UNREADABLE,
    UI_TEXT_FAILURE_LEDGER_MALFORMED,
    UI_TEXT_FAILURE_STORE_FAILED,
    UI_TEXT_FAILURE_NO_SUCH_CATEGORY,
    UI_TEXT_FAILURE_NO_SUCH_NOTE,
    UI_TEXT_FAILURE_NOTE_UNREADABLE,
    UI_TEXT_FAILURE_NOTHING_SELECTED,
    UI_TEXT_FAILURE_NOT_EDITING,
    UI_TEXT_FAILURE_NOTE_MALFORMED,
    UI_TEXT_FAILURE_NOTE_STORE_FAILED,
    UI_TEXT_FAILURE_HISTORY_FAILED,
    UI_TEXT_FAILURE_UNSAVED_CHANGES,
    UI_TEXT_FAILURE_NAME_TAKEN,
    UI_TEXT_FAILURE_LEDGER_STALE,
    UI_TEXT_FAILURE_LEDGER_UNSYNCED,
    UI_TEXT_FAILURE_RENAME_PENDING,
    UI_TEXT_FAILURE_RENAME_UNLOCKED,
    UI_TEXT_FAILURE_RENAME_UNSUPPORTED,
    UI_TEXT_FAILURE_RENAME_IDENTITY_FAILED,
    UI_TEXT_FAILURE_RENAME_JOURNAL_FAILED,
    UI_TEXT_FAILURE_RENAME_JOURNAL_BROKEN,
    UI_TEXT_FAILURE_RENAME_HALTED,
    UI_TEXT_FAILURE_SEARCH_MALFORMED,
    UI_TEXT_FAILURE_FILTERED,
    UI_TEXT_FAILURE_SETTINGS_UNREADABLE,
    UI_TEXT_FAILURE_SETTINGS_STORE_FAILED,
    UI_TEXT_FAILURE_PANE_UNAVAILABLE,
    UI_TEXT_FAILURE_REPLACE_NO_PATTERN,
    UI_TEXT_FAILURE_REPLACE_BAD_PATTERN,
    UI_TEXT_FAILURE_REPLACE_BAD_TEMPLATE,
    UI_TEXT_FAILURE_REPLACE_TIMED_OUT,
    UI_TEXT_FAILURE_REPLACE_TOO_COMPLEX,
    UI_TEXT_FAILURE_REPLACE_TOO_MANY,
    UI_TEXT_FAILURE_REPLACE_TOO_LARGE,
    UI_TEXT_FAILURE_REPLACE_STALE,
    UI_TEXT_FAILURE_REPLACE_BAD_SPAN,
    UI_TEXT_FAILURE_OUT_OF_MEMORY,
    UI_TEXT_FAILURE_NAME_REQUIRED,
    UI_TEXT_FAILURE_INVALID_NAME,
    UI_TEXT_FAILURE_ALREADY_NAMED,
    UI_TEXT_COMMAND_SAVE,
    UI_TEXT_COMMAND_QUIT,
    UI_TEXT_COMMAND_SAVE_QUIT,
    UI_TEXT_COMMAND_FORCE_QUIT,
    UI_TEXT_COMMAND_HELP,
    UI_TEXT_COMMAND_EDIT,
    UI_TEXT_COMMAND_VIEW,
    UI_TEXT_COMMAND_NEW,
    UI_TEXT_COMMAND_SAVE_AS,
    UI_TEXT_COMMAND_RENAME,
    UI_TEXT_COMMAND_FIND,
    UI_TEXT_COMMAND_SET,
    UI_TEXT_COMMAND_TOGGLE_NUMBER,
    UI_TEXT_COMMAND_REPLACE,
    UI_TEXT_COMMAND_SUBSTITUTE,
    UI_TEXT_HELP_PALETTE,
    UI_TEXT_HELP_EDITOR_MOTION,
    UI_TEXT_HELP_GLOBAL_KEYS,
    UI_TEXT_HELP_GLOBAL_FILTER,
    UI_TEXT_HELP_FILTER_FIELD,
    UI_TEXT_HELP_FILTER_LIMITS,
    UI_TEXT_HELP_FILE_KEYS,
    UI_TEXT_HELP_INDEX_COMMAND,
    UI_TEXT_HELP_EX_SET_NUMBER,
    UI_TEXT_HELP_REPLACE_FIELD,
    UI_TEXT_HELP_EX_SUBSTITUTE,
    UI_TEXT_HELP_SEARCH_KEYS,
    UI_TEXT_HELP_SEARCH_STEP,
    UI_TEXT_HELP_SEARCH_FIELD,
    UI_TEXT_HELP_INDEX_MOTION,
    UI_TEXT_HELP_INDEX_FOLD,
    UI_TEXT_HELP_INDEX_SCROLL,
    UI_TEXT_HELP_EDITOR_ESCAPE,
    UI_TEXT_TITLE_UNTITLED,
    UI_TEXT_TITLE_RECOVERING,
    UI_TEXT_CHIP_VIEW,
    UI_TEXT_CHIP_EDIT,
    UI_TEXT_PLACEHOLDER_FILTER,
    UI_TEXT_STATUS_SEARCH_FORWARD,
    UI_TEXT_STATUS_SEARCH_BACKWARD,
    UI_TEXT_STATUS_SEARCH_MALFORMED,
    UI_TEXT_STATUS_SEARCH_BAD_SPAN,
    UI_TEXT_STATUS_SEARCH_NOT_FOUND,
    UI_TEXT_STATUS_SEARCH_FOUND,
    UI_TEXT_ACTION_SEARCH_PREVIOUS,
    UI_TEXT_ACTION_SEARCH_NEXT,
    UI_TEXT_STATUS_REPLACE_POSITION,
    UI_TEXT_STATUS_REPLACE_COUNT,
    UI_TEXT_ACTION_REPLACE_ONE,
    UI_TEXT_ACTION_REPLACE_ALL,
    UI_TEXT_STATUS_COMMAND_NOT_FOUND,
    UI_TEXT_STATUS_PALETTE_CLICK,
    UI_TEXT_STATUS_PALETTE_FILTER,
    UI_TEXT_STATUS_PALETTE_PAGES,
    UI_TEXT_ACTION_KEYS_HIDE,
    UI_TEXT_ACTION_KEYS_SHOW,
    UI_TEXT_ACTION_PALETTE_PREVIOUS,
    UI_TEXT_ACTION_PALETTE_NEXT,
    UI_TEXT_ACTION_OPERATIONS,
    UI_TEXT_APP_LOGO,
    UI_TEXT_GLYPH_MINUS,
    UI_TEXT_GLYPH_PLUS,
    UI_TEXT_PROMPT_PENDING_EXPLANATION,
    UI_TEXT_PROMPT_PENDING_RENAME,
    UI_TEXT_PROMPT_TITLE_FIRST_SAVE,
    UI_TEXT_PROMPT_TITLE_SAVE_AS,
    UI_TEXT_PROMPT_TITLE_RENAME,
    UI_TEXT_PROMPT_HINT_PENDING,
    UI_TEXT_PROMPT_HINT_FIRST_SAVE,
    UI_TEXT_PROMPT_HINT_SAVE_AS,
    UI_TEXT_PROMPT_HINT_RENAME,
    UI_TEXT_PROMPT_ACCEPT_RETRY,
    UI_TEXT_PROMPT_ACCEPT_SAVE,
    UI_TEXT_PROMPT_ACCEPT_RENAME,
    UI_TEXT_PROMPT_CLOSE_PENDING,
    UI_TEXT_PROMPT_CLOSE_CANCEL,
    UI_TEXT_PROMPT_LABEL_NAME,
    UI_TEXT_PROMPT_LABEL_CATEGORY,
    UI_TEXT_APP_NO_MODULE_PATH,
    UI_TEXT_APP_DATA_IN_USE,
    UI_TEXT_APP_RECOVERY_LOCKED,
    UI_TEXT_APP_OUT_OF_MEMORY,
    UI_TEXT_APP_NO_WINDOW,
};

/* 表を 1 回引く。UTF-8 の終端付きで、長さは strlen で取る。表の外の値へは落ちない
 * （ADR 0027 の決定 3 と同じ）。language はこの単位では JA の 1 値だけ。 */
[[nodiscard]] const char *_Nonnull ui_text_line(enum ui_text id, enum folio_language language);
/* 表の文言を写しながら `{k}` `{n}` `{offset}` `{name}` `{from}` `{to}` を埋める（決定 3）。
 * **埋めた内容は再走査しない**（`{k}` という名前のノートが壊れない）。
 * capacity は UTF-8 のバイト数で終端を含む。収まらなければ out を空文字列にして TOO_LONG。
 * 数は 10 進・先頭のゼロ無し・桁区切り無しで、0 は "0"（append_number と同じ規則）。 */
[[nodiscard]] enum ui_text_format_outcome
ui_text_format(const struct ui_text_request *_Nonnull request, char *_Nonnull out, size_t capacity);

#endif
