/* 空カテゴリの削除結果（ADR 0039 補正 5）。REMOVED は OS の受理で、即時不在ではない。 */
#ifndef NENEFOLIO_CATEGORY_REMOVE_OUTCOME_H
#define NENEFOLIO_CATEGORY_REMOVE_OUTCOME_H
enum category_remove_outcome : unsigned char
{
    CATEGORY_REMOVE_REMOVED,
    CATEGORY_REMOVE_ABSENT,
    CATEGORY_REMOVE_HAS_FILES,
    CATEGORY_REMOVE_HISTORY_NOT_RECYCLED,
    CATEGORY_REMOVE_FAILED
};
#endif
